In [38]:
from sklearn.svm import SVC
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
import numpy as np

In [2]:
# import pickle as p
# print(p.__version__)

AttributeError: module 'pickle' has no attribute '__version__'

In [39]:
data = pd.read_csv("../data/diabetes.csv")

In [40]:
data.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [41]:
target = np.array(data['Outcome'])

In [42]:
target = pd.DataFrame(data=target, columns=['target'])

In [43]:
target.head()

target
0       1
1       0
2       1
3       0
4       1

In [44]:
target.shape

(768, 1)

In [45]:
data.drop("Outcome", axis=1, inplace=True)

In [46]:
data.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  
0                     0.627   50  
1                     0.351   31  
2                     0.672   32  
3                     0.167   21  
4                     2.288   33

In [47]:
temp = np.array(data)
temp

array([[  6.   , 148.   ,  72.   , ...,  33.6  ,   0.627,  50.   ],
       [  1.   ,  85.   ,  66.   , ...,  26.6  ,   0.351,  31.   ],
       [  8.   , 183.   ,  64.   , ...,  23.3  ,   0.672,  32.   ],
       ...,
       [  5.   , 121.   ,  72.   , ...,  26.2  ,   0.245,  30.   ],
       [  1.   , 126.   ,  60.   , ...,  30.1  ,   0.349,  47.   ],
       [  1.   ,  93.   ,  70.   , ...,  30.4  ,   0.315,  23.   ]])

In [53]:
X_train,X_test,Y_train, Y_test = train_test_split(np.array(data), np.array(target), random_state=1, test_size=0.1)

In [66]:
X_test.shape

(77, 8)

In [61]:
X_test.shape

(77, 8)

In [54]:
SVM = SVC(random_state=1)
SVM.fit(X_train, Y_train) 

c:\Users\Teddy Dharma\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\utils\validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVC(random_state=1)

In [55]:
SVM.predict(X_test)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1], dtype=int64)

In [56]:
y_pred = SVM.predict(X_test)

In [57]:
cfm = confusion_matrix(Y_test, y_pred)
cfm

array([[46,  2],
       [13, 16]], dtype=int64)

In [62]:
from sklearn.metrics import classification_report
print(classification_report(Y_test,  y_pred))

              precision    recall  f1-score   support

           0       0.78      0.96      0.86        48
           1       0.89      0.55      0.68        29

    accuracy                           0.81        77
   macro avg       0.83      0.76      0.77        77
weighted avg       0.82      0.81      0.79        77



In [68]:
import pickle

with open("model.pkl", "wb") as f:
    pickle.dump(SVM, f)